name: learn-github-actions

on: [ push ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: hello world
        run: echo "hello github actions"

      - name: ls before checkout
        run: |
          ls -al

      - name: checkout
        uses: actions/checkout@v2

      - name: ls after checkout
        run: |
          ls -al

      - name: ls .github directory
        working-directory: ./.github
        run: |
          ls -al

      - name: fill environment variable
        run : |
          cat \<<EOF\n`cat .my_text.txt`\nEOF\n